<?php

namespace Metinet\Bundle\IutBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImportCSVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportCSVRepository extends EntityRepository
{
}
